# VQLHsH4yZHXW_sqg4KSf
# git://github.com/acme/myproject.git#refs/heads/mybranch
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.networks: overlay
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "",
          "ips": [
              "10.16.11.114"
          ],
          "default": true,
          "dns": {}
      }]
  name: kaniko-git
spec:
  containers:
  - name: kaniko-git
    image: 172.16.1.99/gold/kaniko/excutor:latest
    args: [ "--dockerfile=Dockerfile",
            "--context=git://nonetheless:VQLHsH4yZHXW_sqg4KSf@172.16.1.41:10080/app/tos-app-market.git#refs/heads/master",
            "--insecure-git=true",
            "--destination=10.10.32.171:443/stage/tos-app-market:tdc-2.2",
            "--insecure=true",
            "--skip-tls-verify=true",
            "--cache=true",
            "--cache-dir=/cache",
            "--cache-repo=10.10.32.171:443/stage/cache"
          ]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /root/.docker
      - name: dockerfile-storage
        mountPath: /root
      - name: kaniko-cache
        mountPath: /cache        
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: dockerfile-storage
      persistentVolumeClaim:
        claimName: dockerfile-claim
    - name: kaniko-cache
      persistentVolumeClaim:
        claimName: kaniko-cache-claim    


