apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.networks: overlay
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "",
          "ips": [
              "10.16.11.114"
          ],
          "default": true,
          "dns": {}
      }]
  name: kaniko-warm
spec:
  containers:
  - name: kaniko-warmer
    image: 172.16.1.99/gold/kaniko/warmer:latest
    args: ["--cache-dir=/cache",
           "--insecure-pull=true",
           "--skip-tls-verify-pull=true",
           "--image=10.10.32.171:443/stage/tos-app-market:tdc-2.2",
           "--verbosity=debug"]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /secret
      - name: kaniko-cache
        mountPath: /cache
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: .docker/config.json
    - name: dockerfile-storage
      persistentVolumeClaim:
        claimName: dockerfile-claim
    - name: kaniko-cache
      persistentVolumeClaim:
        claimName: kaniko-cache-claim   


